### ISSUE TITLE
possible thread safety bugs: entt is not thread safe

### ISSUE THREAD

**Issue by blockspacer** [Oipo/IdleBossHunter#4]
see https://github.com/skypjack/entt/wiki/Crash-Course:-entity-component-system#multithreading

example: handle_create_company https://github.com/volt-software/IdleBossHunter/blob/0bb6ad5de22e37704d9f40b2e4d7ec3a0e15d649/server/src/game_queue_message_handlers/company/create_company_handler.cpp

```cpp
auto pc_view = es.view<pc_component>();
/// ...
auto company_entt = es.create();
            es.assign<company_component>(company_entt, new_company.id, create_msg->company_name, ibh_flat_map<uint64_t, uint16_t>{{pc.id, COMPANY_ADMIN}}, company_stats);
```

used both at websocket_thread.cpp and server/src/main.cpp

`company_component` modified from multiple threads (for example, in handle_leave_company)

**Comment by Oipo** [comment]
Appreciate taking the time to look through the code!

The reason this is OK is because all game queue message handlers run off the main thread. Therefore, all access to entt is single-threaded.

If entt is accessed outside of the main thread, then yes, that's a potential data race.

**Comment by Oipo** [comment]
See 
https://github.com/volt-software/IdleBossHunter/blob/0bb6ad5de22e37704d9f40b2e4d7ec3a0e15d649/server/src/main.cpp#L161

and
https://github.com/volt-software/IdleBossHunter/blob/0bb6ad5de22e37704d9f40b2e4d7ec3a0e15d649/server/src/main.cpp#L180
